// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    Image: typeof import('./src/components/basicComponents/image/index.vue')['default']
    Text: typeof import('./src/components/basicComponents/text/index.vue')['default']
  }
}

export { }
