// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/basicModule/button/index.vue')['default']
    Image: typeof import('./src/components/basicModule/image/index.vue')['default']
    ModuleRender: typeof import('./src/components/common/ModuleRender.vue')['default']
    Preview: typeof import('./src/components/basicModule/button/preview.vue')['default']
    Text: typeof import('./src/components/basicModule/text/index.vue')['default']
  }
}

export { }
